app/blueprints/main.py
from flask import Blueprint, redirect, url_for, request, render_template, g
import mpld3
import seaborn  # imported for Styling matplotlib plots
import json
from .model import get_events_date_df, get_events_by_source_df, get_events_by_content
# from app.data import video_df

main = Blueprint('main', __name__)


def get_params(request=request):
    params = {}
    params['client'] = request.args.get('client', 'storify.com')
    params['from_date'] = request.args.get('from-date', '2014-09-20')
    params['to_date'] = request.args.get('to-date', '2014-09-26')
    params['content_host'] = request.args.get('content-host', '')
    if not params['content_host']:
        for idx, host in enumerate(get_content_hosts()):
            params['content_host' + str(idx + 1)] = host
    else:
        for idx in range(1, 5):
            params['content_host' + str(idx)] = params['content_host']
    return params


def get_content_hosts():
    hosts = []
    for host in ['instagram.com', 'vine.co', 'youtube.com', 'youtu.be']:
        hosts.append(host)
    return hosts


def get_clients():
    clients = []
    for client in ['2dayfm.com.au', 'change.org', 'conservativetribune.com', \
                'disqus.com', 'edmodo.com', 'fox-sports.massrel.io', 'gamespot.com', \
                'genius.com', 'giantbomb.com', 'indiegogo.com', 'knowyourmeme.com', \
                'lockerdome.com', 'medium.com', 'moviepilot.com', 'rap.genius.com', \
                'redditmedia.com', 'storify.com', 'thescore.com', 'thrillon.com', \
                'up.massrelevance.com', 'vulture.com']:
        clients.append(client)
    return clients


@main.route('/')
def index():
    return render_template('index.html')


@main.route('/slides/')
def slides():
    return render_template('slides.html')


@main.route('/viz-date/')
def viz_date():
    params = get_params(request)
    df = get_events_date_df(g.db_engine, params)
    df = df.unstack(1)
    ax = df.plot(legend=['load', 'play'], figsize=(12, 8))
    ax.set_xlabel('Date')
    mpld3_data = mpld3.fig_to_dict(ax.get_figure())
    table_df = get_events_by_source_df(g.db_engine, params)
    ratio_format = lambda x: '<span class="significant"><bold>%f</bold></span>' % x
    table_html = table_df.head(20).to_html(classes=['table'], formatters={'ratio': ratio_format})
    return render_template('base_viz.html', \
        clients=get_clients(), content_hosts=get_content_hosts(), params=params, \
        data_table=table_html, mpld3_data=json.dumps(mpld3_data))


@main.route('/viz-content/')
def viz_content():
    params = get_params(request)
    df = get_events_by_content(g.db_engine, params)
    ax = df.plot(x='loaded', y='played', kind='scatter', figsize=(12, 8))
    mpld3_data = mpld3.fig_to_dict(ax.get_figure())
    url_format = lambda x: '<a href="%s">%s</a>' % (x, x)
    table_html = df.head(20).to_html(classes=['table'], formatters={'content_url': url_format})
    return render_template('base_viz.html', \
        clients=get_clients(), content_hosts=get_content_hosts(), params=params, \
        data_table=table_html, mpld3_data=json.dumps(mpld3_data))


@main.route('/favicon.ico')
def favicon():
    return redirect(url_for('static', filename='img/favicon.ico'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="description" content="Insight Data Engineering Project"/>
    <meta name="viewport" content="width=1000, initial-scale=1.0, maximum-scale=1.0">

    <title>Dashboard</title>
    <link href="{{url_for('static', filename='public/css/common.css')}}" rel="stylesheet">
    {% block head %}{% endblock head %}
  </head>
  <body>
    <div class="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{url_for('main.index')}}">Ramesh Sampath - Insight @ Embed.ly</a>
            </div>
            <!-- /.navbar-header -->
            <ul class="nav navbar-top-links navbar-right">
              <li class="divider"></li>
              <li><a href="{{url_for('main.slides')}}">Slides</a>
              <li class="divider"></li>
              <li><a href="https://github.com/sampathweb/">Github</a>
              <li class="divider"></li>
              <li><a href="https://twitter.com/sampathweb/">Twitter</a>
              </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a class="active" href="{{url_for('main.index')}}"><i class="fa fa-dashboard fa-fw"></i> Dashboard Home</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Charts<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{{url_for('main.viz_date')}}">Activity by Date</a>
                                </li>
                                <li>
                                    <a href="{{url_for('main.viz_content')}}">Acitivty by Source</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>
      <div id="page-wrapper">
      {% block body %}{% endblock body %}
      </div>
      </div>
    <footer>
      <div class="container">
        <div class="row">
        </div>
      </div>
    </footer>
    <script src="{{url_for('static', filename='public/js/common.js')}}"></script>
    {% block js %}{% endblock js %}
  </body>
</html>

app/templates/base_viz.html
{% extends 'base.html' %}

{% block head %}
{% endblock head %}

{% block body %}
        <h2></h2>
        <form class="form-inline" role="form" method="get">
        <div class="row">
        <div class="col-md-4">
          <div class="form-group">
            <div class="input-group">
              <div class="input-group-addon">Site:</div>
              <select name="client" class="selectpicker showtick" data-width="300px" data-style="btn-inverse">
                {% for client in clients %}
                <option>{{client}}</option>
                {% endfor %}
              </select>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="form-group">
            <div class="input-group">
            <div class="input-group-addon">Host:</div>
            <select name="content-host" class="selectpicker showtick" data-width="200px" data-style="btn-inverse">
              <option></option>
              {% for host in content_hosts %}
              <option>{{host}}</option>
              {% endfor %}
            </select>
          </div>
          </div>
          </div>
        <div class="col-md-2">
          <div class="form-group">
            <div class="input-group">
              <!-- <div class="input-group-addon">Range:</div> -->
              <input name="from-date" class="form-control datepicker" placeholder="From Date" data-date="{{params['from_date']}}" data-date-format="yyyy-mm-dd" value="{{params['from_date']}}">
            </div>
          </div>
        </div>
        <div class="col-md-2">
          <div class="form-group">
            <div class="input-group">
          <input name="to-date" class="form-control datepicker" placeholder="To Date" data-date="{{params['from_date']}}" data-date-format="yyyy-mm-dd" value="{{params['to_date']}}">
            </div>
          </div>
        </div>
        <div class="col-md-1">
          <button type="submit" class="btn btn-primary">Go</button>
        </div>
        </div>
        </form>
      <hr />
    <div class="row">
      <div class="col-md-12">
        <div class="panel">
          <div id="vis"></div>
        </div>
      </div>
    </div>
    {{data_table | safe}}
{% endblock body %}

{% block js %}
  <script type="text/javascript">
  // parse a spec and create a visualization view
      $(function() {
        $('.datepicker').datepicker();
        $('.datepicker').on('changeDate', function(ev){
            $(this).datepicker('hide');
        });
        $('.selectpicker').selectpicker();
        $('select[name="client"]').val("{{params['client']}}");
        $('select[name="content-host"]').val("{{params['content_host']}}");
        $('.selectpicker').selectpicker('refresh');
        chart_data = {{mpld3_data | safe}};
        mpld3.draw_figure("vis", chart_data);
    });
  </script>
{% endblock js %}

app/templates/dataviz.html
{% extends 'base.html' %}

{% block body %}
      <div id="page-wrapper">
      <div class="row">
      <div class="col-md-12">
        <h2></h2>
        <form class="form-inline" role="form" method="get">
          <div class="form-group">
            <div class="input-group">
            <div class="input-group-addon">Website:</div>
            <select name="client" class="selectpicker showtick" data-width="300px" data-style="btn-inverse">
              {% for client in clients %}
              <option>{{client}}</option>
              {% endfor %}
            </select>
          </div>
          </div>
          <div class="form-group">
            <div class="input-group">
              <div class="input-group-addon">Date Range:</div>
              <input name="from-date" class="form-control datepicker" placeholder="From Date" data-date="{{params['from_date']}}" data-date-format="yyyy-mm-dd" value="{{params['from_date']}}">
            </div>
          </div>
          <div class="form-group">
            <label class="sr-only" for="to-date">To Date</label>
              <input name="to-date" class="form-control datepicker" placeholder="To Date" data-date="{{params['from_date']}}" data-date-format="yyyy-mm-dd" value="{{params['to_date']}}">
          </div>
          <button type="submit" class="btn btn-primary">Go</button>
        </form>
      </div>
      </div>
      <hr />
    <div class="row">
      <div class="col-md-12">
        <div class="panel">
          <div id="vis"></div>
        </div>
      </div>
    </div>
    {{data_table | safe}}
{% endblock body %}

{% block js %}
  <script src="http://cdnjs.cloudflare.com/ajax/libs/d3/3.4.11/d3.js"></script>
  <script src="http://mpld3.github.io/js/mpld3.v0.2.js"></script>
  <script type="text/javascript">
  // parse a spec and create a visualization view
      $(function() {
        $('.datepicker').datepicker();
        $('.datepicker').on('changeDate', function(ev){
            $(this).datepicker('hide');
        });
        $('.selectpicker').selectpicker();
        $('select[name="client"]').val("{{params['client']}}");
        $('.selectpicker').selectpicker('refresh');
        chart_data = {{mpld3_data | safe}};
        mpld3.draw_figure("vis", chart_data);
    });
  </script>
{% endblock js %}

app/templates/index.html
{% extends 'base.html' %}
{% block body %}
    <div class="row">
      <div class="col-md-12">
        <h2></h2>
      </div>
    </div>
    <hr />
    <div class="row">
      <div class="col-md-12">
        <ul>
        <li>Data available for dates: 09/20/2014 - 09/26/2014</li>
        <li>Select "Activity by Date" to compare loads and plays across time</li>
        <li>Select "Activity by Source" to compare plays across various content sources such as youtube, instagram, vimeo and vine</li>
        </ul>
      </div>
    </div>
{% endblock body %}

app/templates/slides.html
{% extends 'base.html' %}

{% block body %}
    <div class="row">
      <div class="col-md-12">
        <h2></h2>
    </div>
    <hr />
    <div class="row">
      <div class="col-md-10 col-md-offset-2">
          <h1></h1>
          <iframe src="https://www.slideshare.net/slideshow/embed_code/39669785" width="597" height="486" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe> <div style="margin-bottom:5px"><strong><a href="https://www.github.com/sampathweb" target="_blank">Ramesh Sampath</a></strong>
 </div>
      </div>
    </div>
{% endblock body %}